import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import type { AnalysisResult, TourSynthesis } from "../types.js";
import { readTextIfExists } from "./repository.js";

export interface WriteRepoContextOptions {
  outPath?: string;
  generatedAt?: Date;
}

export interface WriteRepoContextResult {
  path: string;
  contentHash: string;
  gitSha: string | null;
}

async function readGitShortSha(rootPath: string): Promise<string | null> {
  const head = await readTextIfExists(path.join(rootPath, ".git", "HEAD"));
  if (!head) {
    return null;
  }

  const trimmed = head.trim();
  if (trimmed.startsWith("ref: ")) {
    const reference = trimmed.slice(5);
    const sha = await readTextIfExists(path.join(rootPath, ".git", reference));
    return sha ? sha.trim().slice(0, 7) : null;
  }

  return trimmed.slice(0, 7);
}

export function computeContextContentHash(analysis: AnalysisResult): string {
  const stable = JSON.stringify({
    shape: analysis.detection.shape,
    languages: analysis.detection.languages,
    nodes: analysis.spine.nodes,
    edges: analysis.spine.edges,
    subsystems: analysis.subsystems.map((cluster) => ({ key: cluster.key, files: cluster.files }))
  });

  return createHash("sha256").update(stable).digest("hex").slice(0, 12);
}

function renderRepoContext(
  analysis: AnalysisResult,
  synthesis: TourSynthesis,
  contentHash: string,
  gitSha: string | null,
  generatedAt: Date
): string {
  const headerParts = [
    `Auto-generated by spine on ${generatedAt.toISOString().slice(0, 10)}`,
    `content hash: ${contentHash}`
  ];
  if (gitSha) {
    headerParts.push(`commit: ${gitSha}`);
  }

  const lines: string[] = [
    "# Repo context for Claude",
    "",
    `> ${headerParts.join(". ")}.`,
    "> Refresh with `/onboard` (or `npm run onboard -- .`).",
    "> Re-run when this hash no longer matches the current source.",
    "",
    "## Project shape",
    `**${analysis.detection.repoName}** is a \`${analysis.detection.shape}\` written primarily in \`${analysis.detection.languages.join(", ")}\`.`,
    ""
  ];

  if (synthesis.mentalModel) {
    lines.push("## Mental model");
    lines.push(synthesis.mentalModel);
    lines.push("");
  }

  if (analysis.diagram) {
    lines.push("## Verified architecture");
    lines.push(
      `The following ${analysis.spine.nodes.length} files form the verified spine; every edge below is backed by static analysis.`
    );
    lines.push("");
    lines.push("```mermaid");
    lines.push(analysis.diagram.code);
    lines.push("```");
    lines.push("");
  } else if (analysis.spine.nodes.length > 0) {
    lines.push("## Verified spine");
    lines.push(
      `The following ${analysis.spine.nodes.length} files form the verified spine. Diagram generation was skipped or failed.`
    );
    lines.push("");
    for (const node of analysis.spine.nodes) {
      lines.push(`- \`${node}\``);
    }
    lines.push("");
  }

  if (analysis.subsystems.length > 0) {
    lines.push("## Subsystems");
    for (const cluster of analysis.subsystems.slice(0, 10)) {
      lines.push(`- **${cluster.label}** — \`${cluster.pathGlob}\`. ${cluster.skipUnless}`);
    }
    lines.push("");
  }

  if (analysis.entryPoints.length > 0) {
    lines.push("## Entry points");
    for (const entryPoint of analysis.entryPoints) {
      lines.push(`- \`${entryPoint.path}\` — ${entryPoint.reason}`);
    }
    lines.push("");
  }

  lines.push(
    "Tip: this file is a snapshot. If the spine you read here looks stale, re-run `/onboard` to refresh."
  );
  lines.push("");

  return lines.join("\n");
}

export async function writeRepoContextFile(
  rootPath: string,
  analysis: AnalysisResult,
  synthesis: TourSynthesis,
  options: WriteRepoContextOptions = {}
): Promise<WriteRepoContextResult> {
  const contentHash = computeContextContentHash(analysis);
  const gitSha = await readGitShortSha(rootPath);
  const generatedAt = options.generatedAt ?? new Date();
  const markdown = renderRepoContext(analysis, synthesis, contentHash, gitSha, generatedAt);

  const targetPath = options.outPath
    ? path.resolve(options.outPath)
    : path.join(rootPath, ".claude", "REPO_CONTEXT.md");

  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, markdown, "utf8");

  return { path: targetPath, contentHash, gitSha };
}
